### ISSUE TITLE
运行时报这个错

### ISSUE THREAD

**Issue by tangchao0106** [HotBitmapGG/StudyProject#3]
错误:(7, 8) 错误: 类GitHubQueryUserInfo是公共的, 应在名为 GitHubQueryUserInfo.java 的文件中声明

**Comment by tangchao0106** [comment]
大神运行时报这个错啊,什么问题

C:\F\ASdaima\StudyProject-studyRank\app\src\main\java\com\hotbitmapgg\studyproject\hcc\model\GithubQueryUserInfo.java
错误:(7, 8) 错误: 类GitHubQueryUserInfo是公共的, 应在名为 GitHubQueryUserInfo.java 的文件中声明
C:\F\ASdaima\StudyProject-studyRank\app\src\main\java\com\hotbitmapgg\studyproject\hcc\ui\activity\GithubUserInfoActivity.java
错误:(41, 8) 错误: 类GitHubUserInfoActivity是公共的, 应在名为 GitHubUserInfoActivity.java 的文件中声明
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。

**Comment by HotBitmapGG** [comment]
@tangchao0106  这个类其实已经没用了，之前没有及时清理掉,我刚更新了下 ，或者你可以自己把这个类删除掉。
