### ISSUE TITLE
大神,不只那一处没有用到啊

### ISSUE THREAD

**Issue by tangchao0106** [HotBitmapGG/StudyProject#4]
大神,不只这一个类啊,还有好多:(41, 8) 错误: 类GitHubUserInfoActivity是公共的, 应在名为 GitHubUserInfoActivity.java 的文件中声明
C:\F\ASdaima\StudyProject-studyRank\app\src\main\java\com\hotbitmapgg\studyproject\hcc\ui\activity\GithubUserInfoActivity.java

2DOG图片那个还是个小问题

**Comment by HotBitmapGG** [comment]
关闭了.
